// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuO1w2oHf5YjW8y82u_qknCZrjn7xNqVk',
    appId: '1:564309313172:web:19704509d221ea81aed681',
    messagingSenderId: '564309313172',
    projectId: 'assets-elernning-1a64e',
    authDomain: 'assets-elernning-1a64e.firebaseapp.com',
    storageBucket: 'assets-elernning-1a64e.appspot.com',
    measurementId: 'G-YD3B1SZK1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzaV2QUvlUBBdQlRWTHbddbxatyw_MsqI',
    appId: '1:564309313172:android:3a47daf3b7d69a21aed681',
    messagingSenderId: '564309313172',
    projectId: 'assets-elernning-1a64e',
    storageBucket: 'assets-elernning-1a64e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_7AD5uEVPB9fI72C2T8t8uD0F82UYkFc',
    appId: '1:564309313172:ios:7c82dc3d3ed9902baed681',
    messagingSenderId: '564309313172',
    projectId: 'assets-elernning-1a64e',
    storageBucket: 'assets-elernning-1a64e.appspot.com',
    androidClientId: '564309313172-t6fsqhf8e0uv2jc2chqtln9vn7670n8h.apps.googleusercontent.com',
    iosClientId: '564309313172-akdijs04l8o46aodjeiu4p2hb3cs43kj.apps.googleusercontent.com',
    iosBundleId: 'com.example.assetsElerning.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_7AD5uEVPB9fI72C2T8t8uD0F82UYkFc',
    appId: '1:564309313172:ios:334d2f80596a7afbaed681',
    messagingSenderId: '564309313172',
    projectId: 'assets-elernning-1a64e',
    storageBucket: 'assets-elernning-1a64e.appspot.com',
    androidClientId: '564309313172-t6fsqhf8e0uv2jc2chqtln9vn7670n8h.apps.googleusercontent.com',
    iosClientId: '564309313172-m5frfj7nqvtipgp34269acveet3futdg.apps.googleusercontent.com',
    iosBundleId: 'com.example.assetsElerning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuO1w2oHf5YjW8y82u_qknCZrjn7xNqVk',
    appId: '1:564309313172:web:f71114675948e8f4aed681',
    messagingSenderId: '564309313172',
    projectId: 'assets-elernning-1a64e',
    authDomain: 'assets-elernning-1a64e.firebaseapp.com',
    storageBucket: 'assets-elernning-1a64e.appspot.com',
    measurementId: 'G-DQP5PNGHQJ',
  );

}